name: flutter_application_nanny_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you want to publish to pub.dev

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Updated direct dependencies
  characters: ^1.4.1
  material_color_utilities: ^0.13.0
  meta: ^1.17.0
  vector_math: ^2.2.0

  # Other project-specific dependencies
  # (Add any other dependencies you use here)

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Updated dev dependencies
  flutter_lints: ^6.0.0
  leak_tracker: ^11.0.1
  leak_tracker_testing: ^3.0.2
  lints: ^6.0.0
  test_api: ^0.7.6
  vm_service: ^15.0.0

flutter:
  uses-material-design: true
